[package]
name = "messenger-analysis"
version = "0.1.0"
authors = ["Will Taylor <w1ll100@hotmail.co.uk>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
plotlib = "0.4.0"